export const primaryBg = "#0e1321"
export const secondaryBg = "#0cb267"
export const primaryText = "#ffc233"
export const secondaryText = "#fcf2ed"
export const quote = "ScanTrack: Your Partner in Efficient Attendance Management."